name: CI

env:
  IMAGE_TAG: vocabs-main:2.16

on:
  push:
    branches: [main, develop]

jobs:
  # deactivated the build-test job from Skosmos, as it should be run against in the dedicated repo (the one where the submodule Skosmos points to)
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Copy config.ttl
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            cp ./config_production.ttl ./skosmos/dockerfiles/config/config-docker.ttl
          fi
          if [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            cp ./config_development.ttl ./skosmos/dockerfiles/config/config-docker.ttl
          fi
      - name: generate build instructions using herokuish
        run: |
          cp -r ./skosmos/dockerfiles/Dockerfile.ubuntu ./skosmos/Dockerfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./skosmos/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/acdh-oeaw/${{ env.IMAGE_TAG }}
  rancher:
    needs: build_and_push_to_registry
    name: Deploy to rancher
    runs-on: ubuntu-latest
    steps:
    - name: Rancher Deploy Action
      run: |
        curl -i -X POST "${{ secrets.RANCHERURL }}?action=redeploy" -H "Authorization: Bearer ${{ secrets.RANCHER_BARER_TOKEN }}"
